# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/diting/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),diting)

$(call add-radio-file-sha1-checked,radio/abl.img,dc6b359df30151c4965915fb528b48aa2e14ac70)
$(call add-radio-file-sha1-checked,radio/aop.img,f79bf585ad7abd345438d98d2d3c5829770ac33a)
$(call add-radio-file-sha1-checked,radio/aop_config.img,5851208045556bf928dd7daaad406efd6f51be23)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d6fc69370d2c43c4f05481e8f428a55ef38967da)
$(call add-radio-file-sha1-checked,radio/cpucp.img,22fda671f141226f510004c54af0d5d5a5eadb77)
$(call add-radio-file-sha1-checked,radio/devcfg.img,7f5c31634c9f25de57e8ff86099f2fe7bd7d915c)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,178ce07dff3798cea318ce9535fe3923f22c498d)
$(call add-radio-file-sha1-checked,radio/hyp.img,75454c3698fdf49772a0da4674ef358c06cc3253)
$(call add-radio-file-sha1-checked,radio/imagefv.img,6a696c959ff686af63fe4c1b8710f3ccd5ab65d0)
$(call add-radio-file-sha1-checked,radio/keymaster.img,14470aa8273e5fbab568c39ed04e47a19cd2a42d)
$(call add-radio-file-sha1-checked,radio/modem.img,5ea5dede1dd1c799cf41ca9540f8b4e09fb36374)
$(call add-radio-file-sha1-checked,radio/qupfw.img,38af4982e5ab06ba49b5e7f9ebd648cd55e83277)
$(call add-radio-file-sha1-checked,radio/shrm.img,a7292e8474f8af4fba9bc78dc19218cd7730cdf1)
$(call add-radio-file-sha1-checked,radio/tz.img,ca0aeb942f9b0de0cbfcd0b64df56a7575aa8a7d)
$(call add-radio-file-sha1-checked,radio/uefi.img,dbcdcc026c922af655f143a61acb569a94a8c486)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,410a175e32c97bd8377efc49b5cfac1ccc13a885)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,4ce9c2765238bf0dbee3dfb069f0b6ba0e070be1)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,3fc1cfdcf34dc6a3e958c414f8e30cf68f98c99e)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,7487b9db4f0c4654b11b3317dd1f8be646228d6d)

endif
